spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendRiderLocation #name of Method
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic-new
          content-type: application/json
      poller:
        fixed-delay: 5000
    kafka:
      binders:
        brokers: localhost:9092
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
#
#  cloud:
#    function:
#      definition: uppercase
#    function.web.path: /uppercase
